# Generated by Django 6.0.1 on 2026-02-07 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactrequest',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='contactrequest',
            name='plan',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
