# Generated by Django 6.0.1 on 2026-02-07 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_contactrequest_email_alter_contactrequest_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingplan',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
