# Generated by Django 6.0.1 on 2026-02-07 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_pricingplan_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testimonial',
            old_name='author_role',
            new_name='author_position',
        ),
    ]
